---
abstract: 'Generate HTML documentation from Rinci package metadata'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-To-HTML
requires:
  Perinci::To::PackageBase: 0.09
  Rinci: 1.1.11
  Text::Markdown: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Perinci-To-HTML/
  repository: http://github.com/sharyanto/perl-Perinci-To-HTML
version: 0.01
